#!/usr/bin/env python3
"""Generate docs/journal/index.md from entry frontmatter. Never hand-edit the index.

Reads YYYY-MM-DD-*.md (type: journal) and gotchas/*.md (type: gotcha),
groups journal entries by date, lists gotchas alphabetically, and shows each
entry as a link + its one_line payoff. Internal entries are listed but tagged
[internal] so the site build (later) can filter on visibility while the
in-repo index stays complete.

Usage: python3 tools/build_journal_index.py [--check]
  --check: exit 1 if the index on disk is stale (for CI).
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
JOURNAL = ROOT / "docs" / "journal"


def frontmatter(path: Path) -> dict[str, str]:
    text = path.read_text(encoding="utf-8")
    m = re.match(r"\A---\n(.*?)\n---\n", text, re.DOTALL)
    if not m:
        return {}
    fields: dict[str, str] = {}
    for line in m.group(1).splitlines():
        km = re.match(r"^(\w+):\s*(.*)$", line)
        if km:
            fields[km.group(1)] = km.group(2).strip().strip('"')
    return fields


def entry_line(path: Path, fm: dict[str, str], rel_prefix: str = "") -> str:
    title = fm.get("title", path.stem)
    one_line = fm.get("one_line", "")
    tag = " `[internal]`" if fm.get("visibility") == "internal" else ""
    line = f"- [{title}]({rel_prefix}{path.name}){tag}"
    if one_line:
        line += f" — {one_line}"
    return line


def build() -> str:
    journal_entries = []
    for p in sorted(JOURNAL.glob("2*.md")):
        fm = frontmatter(p)
        if fm.get("type") == "journal":
            journal_entries.append((fm.get("date", p.stem[:10]), p, fm))

    gotchas = []
    for p in sorted((JOURNAL / "gotchas").glob("*.md")):
        fm = frontmatter(p)
        if fm.get("type") == "gotcha":
            gotchas.append((p, fm))

    out = [
        "# gyrus journal — index",
        "",
        "<!-- GENERATED by tools/build_journal_index.py — do not edit. -->",
        "",
        f"{len(journal_entries)} journal entries, {len(gotchas)} gotchas. "
        "Read [STYLE.md](STYLE.md) before writing one.",
        "",
        "## Journal",
        "",
    ]
    current_date = None
    for date, p, fm in journal_entries:
        if date != current_date:
            out.append(f"### {date}")
            out.append("")
            current_date = date
        out.append(entry_line(p, fm))
    out += ["", "## Gotchas", ""]
    for p, fm in gotchas:
        out.append(entry_line(p, fm, rel_prefix="gotchas/"))
    out.append("")
    return "\n".join(out)


def main() -> int:
    index_path = JOURNAL / "index.md"
    content = build()
    if "--check" in sys.argv:
        if not index_path.exists() or index_path.read_text(encoding="utf-8") != content:
            print("journal index is stale — run tools/build_journal_index.py", file=sys.stderr)
            return 1
        return 0
    index_path.write_text(content, encoding="utf-8")
    print(f"wrote {index_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
